sap.ui.define([
  "sap/ui/base/ManagedObject",
  "sap/ui/model/json/JSONModel",
  "./Random",
  "sap/m/MessageBox"
], function( ManagedObject, JSONModel, Random, MessageBox )
{
  return ManagedObject.extend( "realmz.Kingdom",
  {
    metadata: {
      properties: {
        player: {type: "Realmz.Player"},
        name:  { type: "string", defaultValue: "Unknown Kingdom" },
        population:   { type:"int", defaultValue: 1000},
        // Products generated by kingdom
        food:      { type: "int",    defaultValue: 1000       },
        science: { type:"int", defaultValue: 0},
        gold:      { type: "int" , defaultValue: 1000},
        intel:      { type: "int" , defaultValue: 0},
        // Adjustable jobs for kingdom population
        peasant: {type: "int", defaultValue: 500},
        scientist: {type: "int", defaultValue: 150, bindable: true},
        merchant: {type: "int", defaultValue: 150},
        spy: {type: "int", defaultValue: 100},
        // Army generates no products
        soldier: {type: "int", defaultValue: 100}
      }
    },
    
    onNextTurn: function() {
      this.manageFood();
    },
    
    manageFood: function() {
      var income = this.getPeasant();
      var needs = (this.getPopulation() * 0.5);
      // var outcome = income - needs;
      var outcome = 0;
      MessageBox.information("Todays food income was " + outcome + " units.");
      this.setFood(this.getFood() + outcome);
      if (this.getFood() == 0) {
        this.starve();
      }
    },
    
    substractFood: function(amount) {
      if (amount > this.getFood()) {
        this.setFood(0);
        this.starve();
      }
      else {
        this.setFood(this.getFood() - amount)
      }
    },
    
    starve: function() {
      var rnd = new Random();
      var maxDeaths = this.getPopulation() * .1;
      var deaths = rnd.nextInt(1, maxDeaths);
      this.setPopulation(this.getPopulation() - deaths);
      MessageBox.error("Your kingdom is hungry your greatness!" + "\n" + deaths + " people have starved to death.");
    },
    
    init: function()
    {
      this.model = new JSONModel({});
      Object.entries( this.getMetadata().getProperties() ).forEach(([ key, value ]) => value.defaultValue !== undefined && this.setProperty( key, value.defaultValue ) );
    },
    
    setProperty: function( key, value )
    {
      ManagedObject.prototype.setProperty.apply( this, arguments );
      this.model.setProperty( '/' + key, value );
    },
    
    generateName: function() {
      var nameArray = ["Middle Earth", "Eden", "Wessex"];
      var name = nameArray[Math.floor(Math.random()*nameArray.length)] 
      this.setName(name);
    }
    
  });
  
  
});